logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: warn
    '[org.jmresler.fbi.nibrs]': debug

spring:
  application:
    name: mmp
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    password: jmlawb36
    username: john
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nibrs
  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  profiles:
    active: ${RUNTIME_ENV:dev}

org:
  jmresler:
    nibrs:
      batch:
        props:
        chunk-size: 10
        allowed-skips: 10
      email:
        server: localhost
        port: 25
        sender: rmic@rocketmail.com
        password: password
        recipients: me, myself, i