logging:
  level:
    root: warn
    org.jmresler.fbi.nibrs: debug
  file:
    name: logs/${spring.application.name}.log

spring:
  application:
    name: batch-data-loader
  batch:
    jdbc:
      initialize-schema: embedded
      platform: h2
    job:
      enabled: false
  datasource:
    nibrs:
      driver-class-name: org.h2.Driver
      name: app
      password: app
      url: jdbc:h2:file:./data/nibrs
      hikari:
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    generate-ddl: true
    database: h2
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

