logging:
  level:
    root: warn
    '[org.jmresler.fbi.nibrs.web]': debug
  file:
    name: logs/${spring.application.name}.log

server:
  servlet:
    context-path: /v1/${spring.application.name}

spring:
  application:
    name: web-tester
  datasource:
    driver-class-name: org.postgresql.Driver
    name: jmres
    password: jmlawb36
    url: jdbc:postgresql://localhost:5432/nibrs
  jpa:
    database: postgresql
    show-sql: true
    open-in-view: true
    generate-ddl: false