logging:
  level:
    root: warn
    '[org.jmresler.fbi.nibrs]': debug
  file:
    name: logs/${spring.application.name}.log

server:
  servlet:
    context-path: /v1/${spring.application.name}

spring:
  application:
    name: web
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jmres
    password: 'password'
    url: jdbc:postgresql://localhost:5432/nibrs
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
