DROP SCHEMA IF EXISTS `nibrs`;
CREATE SCHEMA `nibrs` ;
use `nibrs`;

CREATE TABLE agencies (
    yearly_agency_id INTEGER,
    agency_id BIGINT,
    data_year INTEGER,
    ori CHARACTER VARYING(25),
    legacy_ori CHARACTER VARYING(25),
    covered_by_legacy_ori CHARACTER VARYING(25),
    direct_contributor_flag CHARACTER VARYING(1),
    dormant_flag CHARACTER VARYING(1),
    dormant_year INTEGER,
    reporting_type CHARACTER VARYING(1),
    ucr_agency_name CHARACTER VARYING(100),
    ncic_agency_name CHARACTER VARYING(100),
    pub_agency_name CHARACTER VARYING(100),
    pub_agency_unit CHARACTER VARYING(100),
    agency_status CHARACTER VARYING(1),
    state_id INTEGER,
    state_name CHARACTER VARYING(100),
    state_abbr CHARACTER VARYING(2),
    state_postal_abbr CHARACTER VARYING(2),
    division_code INTEGER,
    division_name CHARACTER VARYING(100),
    region_code INTEGER,
    region_name CHARACTER VARYING(100),
    region_desc CHARACTER VARYING(100),
    agency_type_name CHARACTER VARYING(100),
    population INTEGER,
    submitting_agency_id INTEGER,
    sai CHARACTER VARYING(25),
    submitting_agency_name CHARACTER VARYING(200),
    suburban_area_flag CHARACTER VARYING(1),
    population_group_id INTEGER,
    population_group_code CHARACTER VARYING(2),
    population_group_desc CHARACTER VARYING(100),
    parent_pop_group_code INTEGER,
    parent_pop_group_desc CHARACTER VARYING(100),
    mip_flag CHARACTER VARYING(1),
    pop_sort_order INTEGER,
    summary_rape_def CHARACTER VARYING(1),
    pe_reported_flag CHARACTER VARYING(1),
    male_officer INTEGER,
    male_civilian INTEGER,
    male_total INTEGER,
    female_officer INTEGER,
    female_civilian INTEGER,
    female_total INTEGER,
    officer_rate DECIMAL,
    employee_rate DECIMAL,
    nibrs_cert_date DATE,
    nibrs_start_date DATE,
    nibrs_leoka_start_date DATE,
    nibrs_ct_start_date DATE,
    nibrs_multi_bias_start_date DATE,
    nibrs_off_eth_start_date DATE,
    covered_flag CHARACTER VARYING(1),
    county_name CHARACTER VARYING(100),
    msa_name CHARACTER VARYING(100),
    publishable_flag CHARACTER VARYING(1),
    participated CHARACTER VARYING(1),
    nibrs_participated CHARACTER VARYING(1)
);

CREATE TABLE nibrs_activity_type (
    activity_type_id SMALLINT NOT NULL,
    activity_type_code CHARACTER(2),
    activity_type_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_age (
    age_id SMALLINT NOT NULL,
    age_code CHARACTER(2),
    age_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_arrest_type (
    arrest_type_id SMALLINT NOT NULL,
    arrest_type_code CHARACTER(1),
    arrest_type_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_assignment_type (
    assignment_type_id SMALLINT NOT NULL,
    assignment_type_code CHARACTER(1),
    assignment_type_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_bias_list (
    bias_id SMALLINT NOT NULL,
    bias_code CHARACTER(2),
    bias_name CHARACTER VARYING(100),
    bias_desc CHARACTER VARYING(100)
);

CREATE TABLE nibrs_location_type (
    location_id BIGINT NOT NULL,
    location_code CHARACTER(2),
    location_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_offense_type (
    offense_code CHARACTER VARYING(5) NOT NULL,
    offense_name CHARACTER VARYING(100),
    crime_against CHARACTER VARYING(100),
    ct_flag CHARACTER(1),
    hc_flag CHARACTER(1),
    hc_code CHARACTER VARYING(5),
    offense_category_name CHARACTER VARYING(100),
    offense_group CHARACTER(5)
);

CREATE TABLE nibrs_prop_desc_type (
    prop_desc_id SMALLINT NOT NULL,
    prop_desc_name CHARACTER VARYING(100),
    prop_desc_code CHARACTER(2)
);

CREATE TABLE nibrs_victim_type (
    victim_type_id SMALLINT NOT NULL,
    victim_type_code CHARACTER(1),
    victim_type_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_circumstances (
    circumstances_id SMALLINT NOT NULL,
    circumstances_type CHARACTER(1),
    circumstances_code SMALLINT,
    circumstances_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_cleared_except (
    cleared_except_id SMALLINT NOT NULL,
    cleared_except_code CHARACTER(1),
    cleared_except_name CHARACTER VARYING(100),
    cleared_except_desc CHARACTER VARYING(300)
);

CREATE TABLE nibrs_criminal_act (
    data_year INT,
    criminal_act_id SMALLINT NOT NULL,
    offense_id BIGINT NOT NULL
);

CREATE TABLE nibrs_criminal_act_type (
    criminal_act_id SMALLINT NOT NULL,
    criminal_act_code CHARACTER(1),
    criminal_act_name CHARACTER VARYING(100),
    criminal_act_desc CHARACTER VARYING(300)
);

CREATE TABLE nibrs_drug_measure_type (
    drug_measure_type_id SMALLINT NOT NULL,
    drug_measure_code CHARACTER(2),
    drug_measure_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_ethnicity (
    ethnicity_id SMALLINT NOT NULL,
    ethnicity_code CHARACTER(1),
    ethnicity_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_injury (
    injury_id SMALLINT NOT NULL,
    injury_code CHARACTER(1),
    injury_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_justifiable_force (
    justifiable_force_id SMALLINT NOT NULL,
    justifiable_force_code CHARACTER(1),
    justifiable_force_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_prop_loss_type (
    prop_loss_id SMALLINT NOT NULL,
    prop_loss_name CHARACTER VARYING(100),
    prop_loss_desc CHARACTER VARYING(250)
);

CREATE TABLE nibrs_relationship (
    relationship_id SMALLINT NOT NULL,
    relationship_code CHARACTER(2),
    relationship_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_suspected_drug_type (
    suspected_drug_type_id SMALLINT NOT NULL,
    suspected_drug_code CHARACTER(1),
    suspected_drug_name CHARACTER VARYING(100)
);

CREATE TABLE nibrs_using_list (
    suspect_using_id SMALLINT NOT NULL,
    suspect_using_code CHARACTER(1),
    suspect_using_name CHARACTER VARYING(100)
);


CREATE TABLE nibrs_weapon_type (
    weapon_id SMALLINT NOT NULL,
    weapon_code CHARACTER VARYING(3),
    weapon_name CHARACTER VARYING(100),
    shr_flag CHARACTER(1)
);

CREATE TABLE ref_race (
    race_id SMALLINT NOT NULL,
    race_code CHARACTER VARYING(2) NOT NULL,
    race_desc CHARACTER VARYING(100) NOT NULL,
    sort_order SMALLINT,
    start_year SMALLINT,
    end_year SMALLINT,
    notes CHARACTER VARYING(1000)
);

CREATE TABLE ref_state (
    state_id SMALLINT NOT NULL,
    division_id SMALLINT NOT NULL,
    state_name CHARACTER VARYING(100),
    state_code CHARACTER VARYING(2),
    state_abbr CHARACTER VARYING(2),
    state_postal_abbr CHARACTER VARYING(2),
    state_fips_code CHARACTER VARYING(2),
    state_pub_freq_months SMALLINT,
    change_user CHARACTER VARYING(100)
);

CREATE TABLE nibrs_arrestee (
    data_year INT,
    arrestee_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    arrestee_seq_num BIGINT,
    arrest_date TIMESTAMP,
    arrest_type_id SMALLINT,
    multiple_indicator CHARACTER(1),
    offense_code CHARACTER VARYING(5) NOT NULL,
    age_id SMALLINT NOT NULL,
    age_num SMALLINT,
    sex_code CHARACTER(1),
    race_id SMALLINT NOT NULL,
    ethnicity_id SMALLINT,
    resident_code CHARACTER(1),
    under_18_disposition_code CHARACTER(1),
    clearance_ind CHARACTER(1),
    age_range_low_num SMALLINT,
    age_range_high_num SMALLINT
);

CREATE TABLE nibrs_arrestee_weapon (
    data_year INT,
    arrestee_id BIGINT NOT NULL,
    nibrs_arrestee_weapon_id BIGINT,
    weapon_id SMALLINT NOT NULL
);

CREATE TABLE nibrs_bias_motivation (
    data_year INT,
    bias_id SMALLINT NOT NULL,
    offense_id BIGINT NOT NULL
);

CREATE TABLE nibrs_month (
    data_year INT,
    nibrs_month_id BIGINT NOT NULL,
    agency_id BIGINT NOT NULL,
    month_num SMALLINT NOT NULL,
    inc_data_year INT,
    reported_status CHARACTER VARYING(10),
    report_date TIMESTAMP,
    update_flag CHARACTER(1) DEFAULT NULL,
    orig_format CHARACTER(1) DEFAULT NULL,
    data_home CHARACTER VARYING(10),
    ddocname CHARACTER VARYING(50),
    did BIGINT,
    month_pub_status INT
);

CREATE TABLE nibrs_offender (
    data_year INT,
    offender_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    offender_seq_num SMALLINT,
    age_id SMALLINT,
    age_num CHARACTER(3),
    sex_code CHARACTER(1),
    race_id SMALLINT,
    ethnicity_id SMALLINT,
    age_range_low_num SMALLINT,
    age_range_high_num SMALLINT
);

CREATE TABLE nibrs_offense (
    data_year INT,
    offense_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    offense_code CHARACTER VARYING(5) NOT NULL,
    attempt_complete_flag CHARACTER(1),
    location_id BIGINT NOT NULL,
    num_premises_entered SMALLINT,
    method_entry_code CHARACTER(1)
);

CREATE TABLE nibrs_property (
    data_year INT,
    property_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    prop_loss_id SMALLINT NOT NULL,
    stolen_count SMALLINT,
    recovered_count SMALLINT
);

CREATE TABLE nibrs_property_desc (
    data_year INT,
    property_id BIGINT NOT NULL,
    prop_desc_id SMALLINT NOT NULL,
    property_value BIGINT,
    date_recovered TIMESTAMP,
    nibrs_prop_desc_id BIGINT
);

CREATE TABLE nibrs_suspect_using (
    data_year INT,
    suspect_using_id SMALLINT NOT NULL,
    offense_id BIGINT NOT NULL
);

CREATE TABLE nibrs_suspected_drug (
    data_year INT,
    suspected_drug_type_id SMALLINT NOT NULL,
    property_id BIGINT NOT NULL,
    est_drug_qty DOUBLE PRECISION,
    drug_measure_type_id SMALLINT,
    nibrs_suspected_drug_id BIGINT NOT NULL
);

CREATE TABLE nibrs_victim (
    data_year INT,
    victim_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    victim_seq_num SMALLINT,
    victim_type_id SMALLINT NOT NULL,
    assignment_type_id SMALLINT,
    activity_type_id SMALLINT,
    outside_agency_id BIGINT,
    age_id SMALLINT,
    age_num CHARACTER VARYING(2),
    sex_code CHARACTER(1),
    race_id SMALLINT,
    ethnicity_id SMALLINT,
    resident_status_code CHARACTER(1),
    age_range_low_num SMALLINT,
    age_range_high_num SMALLINT
);

CREATE TABLE nibrs_victim_circumstances (
    data_year INT,
    victim_id BIGINT NOT NULL,
    circumstances_id SMALLINT NOT NULL,
    justifiable_force_id SMALLINT
);

CREATE TABLE nibrs_victim_injury (
    data_year INT,
    victim_id BIGINT NOT NULL,
    injury_id SMALLINT NOT NULL
);

CREATE TABLE nibrs_victim_offender_rel (
    data_year INT,
    victim_id BIGINT NOT NULL,
    offender_id BIGINT NOT NULL,
    relationship_id SMALLINT NOT NULL,
    nibrs_victim_offender_id BIGINT
);

CREATE TABLE nibrs_victim_offense (
    data_year INT,
    victim_id BIGINT NOT NULL,
    offense_id BIGINT NOT NULL
);

CREATE TABLE nibrs_weapon (
    data_year INT,
    weapon_id SMALLINT NOT NULL,
    offense_id BIGINT NOT NULL,
    nibrs_weapon_id BIGINT
);

CREATE TABLE nibrs_incident (
	data_year int,
    agency_id bigint NOT NULL,
    incident_id bigint NOT NULL,
    nibrs_month_id bigint NOT NULL,
    cargo_theft_flag character(1),
    submission_date timestamp,
    incident_date timestamp,
    report_date_flag character(1),
    incident_hour smallint,
    cleared_except_id smallint NOT NULL,
    cleared_except_date timestamp,
    incident_status character varying(100), -- smallint
    data_home character(1),
    orig_format character(1),
    did bigint
);


  ALTER TABLE NIBRS_SUSPECTED_DRUG ADD CONSTRAINT NIBRS_SUSPECTED_DRUG_PK PRIMARY KEY (NIBRS_SUSPECTED_DRUG_ID);

  ALTER TABLE NIBRS_RELATIONSHIP ADD CONSTRAINT NIBRS_RELATIONSHIP_PK PRIMARY KEY (RELATIONSHIP_ID);

  ALTER TABLE NIBRS_DRUG_MEASURE_TYPE ADD CONSTRAINT NIBRS_DRUG_MEASURE_TYPE_PK PRIMARY KEY (DRUG_MEASURE_TYPE_ID);

  ALTER TABLE NIBRS_USING_LIST ADD CONSTRAINT NIBRS_SUSPECTED_USING_PK PRIMARY KEY (SUSPECT_USING_ID);

  ALTER TABLE NIBRS_PROP_LOSS_TYPE ADD CONSTRAINT NIBRS_PROP_LOSS_TYPE_PK PRIMARY KEY (PROP_LOSS_ID);

  ALTER TABLE NIBRS_ETHNICITY ADD CONSTRAINT NIBRS_ETH_PK PRIMARY KEY (ETHNICITY_ID);

  ALTER TABLE NIBRS_PROPERTY ADD CONSTRAINT NIBRS_PROPERTY_PK PRIMARY KEY (PROPERTY_ID);

  ALTER TABLE NIBRS_CRIMINAL_ACT ADD CONSTRAINT NIBRS_CRIMINAL_ACT_PK PRIMARY KEY (CRIMINAL_ACT_ID, OFFENSE_ID);

  ALTER TABLE NIBRS_OFFENSE_TYPE ADD CONSTRAINT NIBRS_OFFENSE_TYPE_PK PRIMARY KEY (offense_code);

  ALTER TABLE NIBRS_CRIMINAL_ACT_TYPE ADD CONSTRAINT NIBRS_CRIMINAL_ACT_TYPE_PK PRIMARY KEY (CRIMINAL_ACT_ID);

  ALTER TABLE NIBRS_PROPERTY_DESC ADD CONSTRAINT NIBRS_PROPERTY_DESC_PK PRIMARY KEY (property_id, prop_desc_id);

  ALTER TABLE NIBRS_INCIDENT ADD CONSTRAINT NIBRS_INCIDENT_PK PRIMARY KEY (INCIDENT_ID);

  ALTER TABLE NIBRS_BIAS_MOTIVATION ADD CONSTRAINT NIBRS_BIAS_MOTIVATION_PK PRIMARY KEY (BIAS_ID, OFFENSE_ID);

  ALTER TABLE NIBRS_SUSPECT_USING ADD CONSTRAINT NIBRS_SUSPECT_USING_PK PRIMARY KEY (SUSPECT_USING_ID, OFFENSE_ID);

  ALTER TABLE NIBRS_VICTIM_TYPE ADD CONSTRAINT NIBRS_VICTIM_TYPE_PK PRIMARY KEY (VICTIM_TYPE_ID);

  ALTER TABLE NIBRS_INJURY ADD CONSTRAINT NIBRS_INJURY_PK PRIMARY KEY (INJURY_ID);

  ALTER TABLE NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_PK PRIMARY KEY (OFFENDER_ID);

  ALTER TABLE NIBRS_CIRCUMSTANCES ADD CONSTRAINT NIBRS_CIRCUMSTANCES_PK PRIMARY KEY (CIRCUMSTANCES_ID);

  ALTER TABLE NIBRS_ACTIVITY_TYPE ADD CONSTRAINT NIBRS_ACTIVITY_TYPE_PK PRIMARY KEY (ACTIVITY_TYPE_ID);

  ALTER TABLE NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_PK PRIMARY KEY (ARRESTEE_ID);

  ALTER TABLE NIBRS_WEAPON_TYPE ADD CONSTRAINT NIBRS_WEAPON_TYPE_PK PRIMARY KEY (WEAPON_ID);

  ALTER TABLE NIBRS_BIAS_LIST ADD CONSTRAINT NIBRS_BIAS_LIST_PK PRIMARY KEY (BIAS_ID);

  ALTER TABLE NIBRS_ARREST_TYPE ADD CONSTRAINT NIBRS_ARREST_TYPE_PK PRIMARY KEY (ARREST_TYPE_ID);

  ALTER TABLE NIBRS_VICTIM_INJURY ADD CONSTRAINT NIBRS_VICTIM_INJURY_PK PRIMARY KEY (VICTIM_ID, INJURY_ID);

  ALTER TABLE NIBRS_OFFENSE ADD CONSTRAINT NIBRS_OFFENSE_PK PRIMARY KEY (OFFENSE_ID);

  ALTER TABLE NIBRS_VICTIM_OFFENDER_REL ADD CONSTRAINT NIBRS_VICTIM_OFFENDER_REL_PK PRIMARY KEY (victim_id, offender_id);

  ALTER TABLE NIBRS_CLEARED_EXCEPT ADD CONSTRAINT NIBRS_CLEARED_EXCEPT_PK PRIMARY KEY (CLEARED_EXCEPT_ID);

  ALTER TABLE NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_PK PRIMARY KEY (VICTIM_ID);

  ALTER TABLE NIBRS_MONTH ADD CONSTRAINT NIBRS_MONTH_PK PRIMARY KEY (did);

  ALTER TABLE NIBRS_AGE ADD CONSTRAINT NIBRS_AGE_PK PRIMARY KEY (AGE_ID);

  ALTER TABLE NIBRS_PROP_DESC_TYPE ADD CONSTRAINT NIBRS_PROP_DESC_TYPE_PK PRIMARY KEY (PROP_DESC_ID);

  ALTER TABLE NIBRS_VICTIM_CIRCUMSTANCES ADD CONSTRAINT NIBRS_VICTIM_CIRCUMSTANCES_PK PRIMARY KEY (VICTIM_ID, CIRCUMSTANCES_ID);

  ALTER TABLE NIBRS_ARRESTEE_WEAPON ADD CONSTRAINT NIBRS_ARRESTEE_WEAPON_PK PRIMARY KEY (arrestee_id, weapon_id);

  ALTER TABLE NIBRS_SUSPECTED_DRUG_TYPE ADD CONSTRAINT NIBRS_SUSPECTED_DRUG_TYPE_PK PRIMARY KEY (SUSPECTED_DRUG_TYPE_ID);

  ALTER TABLE NIBRS_VICTIM_OFFENSE ADD CONSTRAINT NIBRS_VICTIM_OFFENSE_PK PRIMARY KEY (VICTIM_ID, OFFENSE_ID);

  ALTER TABLE NIBRS_LOCATION_TYPE ADD CONSTRAINT NIBRS_LOCATION_TYPE_PK PRIMARY KEY (LOCATION_ID);

  ALTER TABLE NIBRS_ASSIGNMENT_TYPE ADD CONSTRAINT NIBRS_ASSIGN_TYPE_PK PRIMARY KEY (ASSIGNMENT_TYPE_ID);

  ALTER TABLE NIBRS_WEAPON ADD CONSTRAINT NIBRS_WEAPON_PK PRIMARY KEY (weapon_id, offense_id);

  ALTER TABLE REF_RACE ADD CONSTRAINT REF_RACE_PK PRIMARY KEY (RACE_ID);

  ALTER TABLE REF_STATE ADD CONSTRAINT REF_STATE_PK PRIMARY KEY (STATE_ID);

  ALTER TABLE AGENCIES ADD CONSTRAINT AGENCIES_PK PRIMARY KEY (agency_id);

  ALTER TABLE NIBRS_JUSTIFIABLE_FORCE ADD CONSTRAINT NIBRS_JUSTIFIABLE_FORCE_PK PRIMARY KEY (JUSTIFIABLE_FORCE_ID);
  
  ALTER TABLE NIBRS_ARRESTEE_WEAPON ADD CONSTRAINT NIBRS_ARREST_WEAP_ARREST_FK FOREIGN KEY (ARRESTEE_ID)
	  REFERENCES NIBRS_ARRESTEE (ARRESTEE_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_ARRESTEE_WEAPON ADD CONSTRAINT NIBRS_ARREST_WEAP_TYPE_FK FOREIGN KEY (WEAPON_ID)
	  REFERENCES NIBRS_WEAPON_TYPE (WEAPON_ID);

  ALTER TABLE NIBRS_PROPERTY_DESC ADD CONSTRAINT NIBRS_PROP_DESC_PROP_FK FOREIGN KEY (PROPERTY_ID)
	  REFERENCES NIBRS_PROPERTY (PROPERTY_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_PROPERTY_DESC ADD CONSTRAINT NIBRS_PROP_DESC_TYPE_FK FOREIGN KEY (PROP_DESC_ID)
	  REFERENCES NIBRS_PROP_DESC_TYPE (PROP_DESC_ID);

  ALTER TABLE NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_AGE_FK FOREIGN KEY (AGE_ID)
	  REFERENCES NIBRS_AGE (AGE_ID);

  ALTER TABLE NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_ARREST_TYPE_FK FOREIGN KEY (ARREST_TYPE_ID)
	  REFERENCES NIBRS_ARREST_TYPE (ARREST_TYPE_ID);

  ALTER TABLE NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_ETHNICITY_FK FOREIGN KEY (ETHNICITY_ID)
	  REFERENCES NIBRS_ETHNICITY (ETHNICITY_ID);

  ALTER TABLE NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_INC_FK FOREIGN KEY (INCIDENT_ID)
	  REFERENCES NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_RACE_FK FOREIGN KEY (RACE_ID)
	  REFERENCES REF_RACE (RACE_ID);

  ALTER TABLE NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_OFFENSE_TYPE_FK FOREIGN KEY (offense_code)
	  REFERENCES NIBRS_OFFENSE_TYPE (offense_code);

  ALTER TABLE NIBRS_SUSPECTED_DRUG ADD CONSTRAINT NIBRS_SUSP_DRUG_MEAS_TYPE_FK FOREIGN KEY (DRUG_MEASURE_TYPE_ID)
	  REFERENCES NIBRS_DRUG_MEASURE_TYPE (DRUG_MEASURE_TYPE_ID);

  ALTER TABLE NIBRS_SUSPECTED_DRUG ADD CONSTRAINT NIBRS_SUSP_DRUG_PROP_FK FOREIGN KEY (PROPERTY_ID)
	  REFERENCES NIBRS_PROPERTY (PROPERTY_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_SUSPECTED_DRUG ADD CONSTRAINT NIBRS_SUSP_DRUG_TYPE_FK FOREIGN KEY (SUSPECTED_DRUG_TYPE_ID)
	  REFERENCES NIBRS_SUSPECTED_DRUG_TYPE (SUSPECTED_DRUG_TYPE_ID);

  ALTER TABLE NIBRS_PROPERTY ADD CONSTRAINT NIBRS_PROPERTY_INC_FK FOREIGN KEY (INCIDENT_ID)
	  REFERENCES NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_PROPERTY ADD CONSTRAINT NIBRS_PROPERTY_LOSS_TYPE_FK FOREIGN KEY (PROP_LOSS_ID)
	  REFERENCES NIBRS_PROP_LOSS_TYPE (PROP_LOSS_ID);

  ALTER TABLE NIBRS_CRIMINAL_ACT ADD CONSTRAINT NIBRS_CRIMINAL_ACT_OFFENSE_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_CRIMINAL_ACT ADD CONSTRAINT NIBRS_CRIMINAL_ACT_TYPE_FK FOREIGN KEY (CRIMINAL_ACT_ID)
	  REFERENCES NIBRS_CRIMINAL_ACT_TYPE (CRIMINAL_ACT_ID);

  ALTER TABLE NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_AGE_FK FOREIGN KEY (AGE_ID)
	  REFERENCES NIBRS_AGE (AGE_ID);

  ALTER TABLE NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_ETHNICITY_FK FOREIGN KEY (ETHNICITY_ID)
	  REFERENCES NIBRS_ETHNICITY (ETHNICITY_ID);

  ALTER TABLE NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_NIBRS_INCI_FK1 FOREIGN KEY (INCIDENT_ID)
	  REFERENCES NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_RACE_FK FOREIGN KEY (RACE_ID)
	  REFERENCES REF_RACE (RACE_ID);

  ALTER TABLE NIBRS_VICTIM_INJURY ADD CONSTRAINT NIBRS_VIC_INJURY_NIBRS_INJ_FK FOREIGN KEY (INJURY_ID)
	  REFERENCES NIBRS_INJURY (INJURY_ID);

  ALTER TABLE NIBRS_VICTIM_INJURY ADD CONSTRAINT NIBRS_VIC_INJURY_NIBRS_VIC_FK FOREIGN KEY (VICTIM_ID)
	  REFERENCES NIBRS_VICTIM (VICTIM_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_WEAPON ADD CONSTRAINT NIBRS_WEAP_WEAP_TYPE_FK FOREIGN KEY (WEAPON_ID)
	  REFERENCES NIBRS_WEAPON_TYPE (WEAPON_ID);

  ALTER TABLE NIBRS_WEAPON ADD CONSTRAINT NIBRS_WEAP_OFF_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_VICTIM_CIRCUMSTANCES ADD CONSTRAINT NIBRS_VIC_CIRC_NIBRS_VIC_FK FOREIGN KEY (VICTIM_ID)
	  REFERENCES NIBRS_VICTIM (VICTIM_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_VICTIM_CIRCUMSTANCES ADD CONSTRAINT NIBRS_VICTIM_CIRC_JUST_HOM_FK FOREIGN KEY (JUSTIFIABLE_FORCE_ID)
	  REFERENCES NIBRS_JUSTIFIABLE_FORCE (JUSTIFIABLE_FORCE_ID);

  ALTER TABLE NIBRS_VICTIM_CIRCUMSTANCES ADD CONSTRAINT NIBRS_VIC_CIRC_NIBRS_CIRC_FK FOREIGN KEY (CIRCUMSTANCES_ID)
	  REFERENCES NIBRS_CIRCUMSTANCES (CIRCUMSTANCES_ID);

  ALTER TABLE NIBRS_SUSPECT_USING ADD CONSTRAINT NIBRS_SUSPECT_USING_OFF_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_SUSPECT_USING ADD CONSTRAINT NIBRS_SUSPECT_USING_LIST_FK FOREIGN KEY (SUSPECT_USING_ID)
	  REFERENCES NIBRS_USING_LIST (SUSPECT_USING_ID);

  ALTER TABLE NIBRS_OFFENSE ADD CONSTRAINT NIBRS_OFFENSE_INC_FK1 FOREIGN KEY (INCIDENT_ID)
	  REFERENCES NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_OFFENSE ADD CONSTRAINT NIBRS_OFFENSE_LOC_TYPE_FK FOREIGN KEY (LOCATION_ID)
	  REFERENCES NIBRS_LOCATION_TYPE (LOCATION_ID);

  ALTER TABLE NIBRS_OFFENSE ADD CONSTRAINT NIBRS_OFFENSE_OFF_TYPE_FK FOREIGN KEY (offense_code)
	  REFERENCES NIBRS_OFFENSE_TYPE (offense_code);

  ALTER TABLE NIBRS_VICTIM_OFFENDER_REL ADD CONSTRAINT NIBRS_VICTIM_OFF_REL_VIC_FK FOREIGN KEY (VICTIM_ID)
	  REFERENCES NIBRS_VICTIM (VICTIM_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_VICTIM_OFFENDER_REL ADD CONSTRAINT NIBRS_VICTIM_OFF_REL_OFF_FK FOREIGN KEY (OFFENDER_ID)
	  REFERENCES NIBRS_OFFENDER (OFFENDER_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_VICTIM_OFFENDER_REL ADD CONSTRAINT NIBRS_VICTIM_OFF_REL_REL_FK FOREIGN KEY (RELATIONSHIP_ID)
	  REFERENCES NIBRS_RELATIONSHIP (RELATIONSHIP_ID);

  ALTER TABLE NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIMS_VIC_TYPE_FK FOREIGN KEY (VICTIM_TYPE_ID)
	  REFERENCES NIBRS_VICTIM_TYPE (VICTIM_TYPE_ID);

  ALTER TABLE NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_ACT_TYPE_FK FOREIGN KEY (ACTIVITY_TYPE_ID)
	  REFERENCES NIBRS_ACTIVITY_TYPE (ACTIVITY_TYPE_ID);

  ALTER TABLE NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_AGE_FK FOREIGN KEY (AGE_ID)
	  REFERENCES NIBRS_AGE (AGE_ID);

  ALTER TABLE NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_ASSIGN_TYPE_FK FOREIGN KEY (ASSIGNMENT_TYPE_ID)
	  REFERENCES NIBRS_ASSIGNMENT_TYPE (ASSIGNMENT_TYPE_ID);

  ALTER TABLE NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_ETHNICITY_FK FOREIGN KEY (ETHNICITY_ID)
	  REFERENCES NIBRS_ETHNICITY (ETHNICITY_ID);

  ALTER TABLE NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_RACE_FK FOREIGN KEY (RACE_ID)
	  REFERENCES REF_RACE (RACE_ID);

  ALTER TABLE NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_INC_FK FOREIGN KEY (INCIDENT_ID)
	  REFERENCES NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_MONTH ADD CONSTRAINT NIBRS_MONTH_AGENCY_FK FOREIGN KEY (AGENCY_ID)
	  REFERENCES AGENCIES (AGENCY_ID);

  ALTER TABLE NIBRS_INCIDENT ADD CONSTRAINT NIBRS_INCIDENT_AGENCY_FK FOREIGN KEY (AGENCY_ID)
	  REFERENCES AGENCIES (AGENCY_ID);

  ALTER TABLE NIBRS_INCIDENT ADD CONSTRAINT NIBRS_INCIDENT_CLEAR_EX_FK FOREIGN KEY (CLEARED_EXCEPT_ID)
	  REFERENCES NIBRS_CLEARED_EXCEPT (CLEARED_EXCEPT_ID);

  ALTER TABLE NIBRS_INCIDENT ADD CONSTRAINT NIBRS_INCIDENT_MONTH_FK FOREIGN KEY (did)
	  REFERENCES NIBRS_MONTH (did) ON DELETE CASCADE;

  ALTER TABLE NIBRS_VICTIM_OFFENSE ADD CONSTRAINT NIBRS_VIC_OFF_NIBRS_VIC_FK FOREIGN KEY (VICTIM_ID)
	  REFERENCES NIBRS_VICTIM (VICTIM_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_VICTIM_OFFENSE ADD CONSTRAINT NIBRS_VIC_OFF_NIBRS_OFF_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_BIAS_MOTIVATION ADD CONSTRAINT NIBRS_BIAS_MOT_OFFENSE_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE NIBRS_BIAS_MOTIVATION ADD CONSTRAINT NIBRS_BIAS_MOT_LIST_FK FOREIGN KEY (BIAS_ID)
	  REFERENCES NIBRS_BIAS_LIST (BIAS_ID);

